-- Criar tabelas do Fechamento Diário

CREATE TABLE IF NOT EXISTS `fechamentos_diarios` (
  `id` int AUTO_INCREMENT NOT NULL,
  `data` date NOT NULL,
  `status` enum('pendente','conciliado','com_divergencia') NOT NULL DEFAULT 'pendente',
  `totalSistema` int NOT NULL DEFAULT 0,
  `totalDinheiro` int NOT NULL DEFAULT 0,
  `totalPix` int NOT NULL DEFAULT 0,
  `totalDebito` int NOT NULL DEFAULT 0,
  `totalCreditoVista` int NOT NULL DEFAULT 0,
  `totalCreditoParcelado` int NOT NULL DEFAULT 0,
  `totalRede` int,
  `totalRedeDebito` int,
  `totalRedeCredito` int,
  `quantidadeVendasOk` int NOT NULL DEFAULT 0,
  `quantidadeDivergencias` int NOT NULL DEFAULT 0,
  `quantidadeNaoLancadas` int NOT NULL DEFAULT 0,
  `quantidadeFantasma` int NOT NULL DEFAULT 0,
  `observacoes` text,
  `conciliadoPorId` int,
  `conciliadoPorNome` varchar(255),
  `conciliadoEm` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fechamentos_diarios_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `transacoes_rede` (
  `id` int AUTO_INCREMENT NOT NULL,
  `fechamentoDiarioId` int NOT NULL,
  `dataVenda` datetime NOT NULL,
  `horaVenda` varchar(10),
  `statusVenda` varchar(50),
  `valorOriginal` int NOT NULL,
  `valorAtualizado` int,
  `valorLiquido` int,
  `modalidade` varchar(20),
  `tipo` varchar(50),
  `numeroParcelas` int DEFAULT 1,
  `bandeira` varchar(50),
  `nsuCv` varchar(50),
  `taxaMdr` varchar(20),
  `valorMdr` int,
  `numeroAutorizacao` varchar(50),
  `numeroEstabelecimento` varchar(50),
  `numeroCartao` varchar(50),
  `tid` varchar(100),
  `vendaId` int,
  `pagamentoId` int,
  `statusMatching` enum('ok','divergencia_valor','nao_lancado','duplicado'),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `transacoes_rede_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `divergencias_fechamento` (
  `id` int AUTO_INCREMENT NOT NULL,
  `fechamentoDiarioId` int NOT NULL,
  `tipoDivergencia` enum('valor_diferente','nao_lancado','venda_fantasma','duplicado') NOT NULL,
  `vendaId` int,
  `pagamentoId` int,
  `transacaoRedeId` int,
  `valorEsperado` int,
  `valorEncontrado` int,
  `diferenca` int,
  `cvNsu` varchar(50),
  `descricao` text,
  `statusResolucao` enum('pendente','aprovado','corrigido','ignorado') NOT NULL DEFAULT 'pendente',
  `justificativa` text,
  `resolvidoPorId` int,
  `resolvidoPorNome` varchar(255),
  `resolvidoEm` timestamp,
  `observacoes` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `divergencias_fechamento_id` PRIMARY KEY(`id`)
);
