CREATE TABLE `extratos_uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fechamentoId` int NOT NULL,
	`tipo` enum('itau_entrada','itau_saida','rede_recebimentos') NOT NULL,
	`nomeArquivo` varchar(255) NOT NULL,
	`urlArquivo` text NOT NULL,
	`processado` boolean NOT NULL DEFAULT false,
	`dadosProcessados` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `extratos_uploads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fechamentos_mensais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mes` int NOT NULL,
	`ano` int NOT NULL,
	`tipo` enum('vendas','conta_bancaria') NOT NULL,
	`receitaCartoes` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaPix` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaDinheiro` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaRendimento` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaPlataforma` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaPagseguro` decimal(15,2) NOT NULL DEFAULT '0',
	`receitaSantander` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaTarifaCartao` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaOutrasTarifas` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaImpostos` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaMaquiadora` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaOperacaoFora` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaInvestimentos` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaEstorno` decimal(15,2) NOT NULL DEFAULT '0',
	`despesaTransfSantander` decimal(15,2) NOT NULL DEFAULT '0',
	`impostosIss` decimal(15,2) NOT NULL DEFAULT '0',
	`impostosPis` decimal(15,2) NOT NULL DEFAULT '0',
	`impostosCofins` decimal(15,2) NOT NULL DEFAULT '0',
	`impostosCsll` decimal(15,2) NOT NULL DEFAULT '0',
	`impostosIrpj` decimal(15,2) NOT NULL DEFAULT '0',
	`aliquotaIrpjEstimada` decimal(5,2) NOT NULL DEFAULT '0',
	`aliquotaIrpjReal` decimal(5,2) NOT NULL DEFAULT '0',
	`criadoPorId` int NOT NULL,
	`criadoPorNome` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fechamentos_mensais_id` PRIMARY KEY(`id`)
);
