DROP TABLE `agendamentos`;--> statement-breakpoint
DROP TABLE `anexos_despesas`;--> statement-breakpoint
DROP TABLE `briefing_evento`;--> statement-breakpoint
DROP TABLE `briefing_formando`;--> statement-breakpoint
DROP TABLE `briefing_grupo`;--> statement-breakpoint
DROP TABLE `cenarios`;--> statement-breakpoint
DROP TABLE `cidades`;--> statement-breakpoint
DROP TABLE `configMaquiagem`;--> statement-breakpoint
DROP TABLE `configMaquiagemTurma`;--> statement-breakpoint
DROP TABLE `cursos`;--> statement-breakpoint
DROP TABLE `despesas`;--> statement-breakpoint
DROP TABLE `despesas_v2`;--> statement-breakpoint
DROP TABLE `despesas_v2_anexos`;--> statement-breakpoint
DROP TABLE `despesas_v2_datas`;--> statement-breakpoint
DROP TABLE `despesas_v2_historico`;--> statement-breakpoint
DROP TABLE `despesas_v2_turmas`;--> statement-breakpoint
DROP TABLE `eventos`;--> statement-breakpoint
DROP TABLE `execucao_formando`;--> statement-breakpoint
DROP TABLE `extratos_uploads`;--> statement-breakpoint
DROP TABLE `fechamentos_mensais`;--> statement-breakpoint
DROP TABLE `formandos`;--> statement-breakpoint
DROP TABLE `fornecedores`;--> statement-breakpoint
DROP TABLE `fotos_formando`;--> statement-breakpoint
DROP TABLE `historico_observacoes`;--> statement-breakpoint
DROP TABLE `horarios_briefing`;--> statement-breakpoint
DROP TABLE `instituicoes`;--> statement-breakpoint
DROP TABLE `itensVenda`;--> statement-breakpoint
DROP TABLE `locais`;--> statement-breakpoint
DROP TABLE `notificacoes`;--> statement-breakpoint
DROP TABLE `pagamentos`;--> statement-breakpoint
DROP TABLE `permissoes`;--> statement-breakpoint
DROP TABLE `permissoes_configuracoes`;--> statement-breakpoint
DROP TABLE `permissoes_relatorios`;--> statement-breakpoint
DROP TABLE `produtos`;--> statement-breakpoint
DROP TABLE `reunioes`;--> statement-breakpoint
DROP TABLE `sequencia_ci`;--> statement-breakpoint
DROP TABLE `servicosAgendados`;--> statement-breakpoint
DROP TABLE `servicos_execucao`;--> statement-breakpoint
DROP TABLE `tabela_preco_fornecedores`;--> statement-breakpoint
DROP TABLE `taxasCartao`;--> statement-breakpoint
DROP TABLE `tipos_cenario`;--> statement-breakpoint
DROP TABLE `tipos_evento`;--> statement-breakpoint
DROP TABLE `tipos_servico`;--> statement-breakpoint
DROP TABLE `turmas`;--> statement-breakpoint
DROP TABLE `vendas`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `status`;