CREATE TABLE `divergencias_fechamento` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fechamentoDiarioId` int NOT NULL,
	`tipoDivergencia` enum('valor_diferente','nao_lancado','venda_fantasma','data_incorreta') NOT NULL,
	`vendaId` int,
	`pagamentoId` int,
	`transacaoRedeId` int,
	`valorEsperado` int,
	`valorEncontrado` int,
	`diferenca` int,
	`cvNsu` varchar(50),
	`descricao` text,
	`statusResolucao` enum('pendente','aprovado','corrigido','ignorado') NOT NULL DEFAULT 'pendente',
	`justificativa` text,
	`resolvidoPorId` int,
	`resolvidoPorNome` varchar(255),
	`resolvidoEm` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `divergencias_fechamento_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fechamentos_diarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`data` date NOT NULL,
	`status` enum('pendente','conciliado','com_divergencia') NOT NULL DEFAULT 'pendente',
	`totalSistema` int NOT NULL,
	`totalDinheiro` int NOT NULL DEFAULT 0,
	`totalPix` int NOT NULL DEFAULT 0,
	`totalDebito` int NOT NULL DEFAULT 0,
	`totalCreditoVista` int NOT NULL DEFAULT 0,
	`totalCreditoParcelado` int NOT NULL DEFAULT 0,
	`totalRede` int,
	`totalRedeDebito` int,
	`totalRedeCredito` int,
	`quantidadeVendasOk` int DEFAULT 0,
	`quantidadeDivergencias` int DEFAULT 0,
	`quantidadeNaoLancadas` int DEFAULT 0,
	`quantidadeFantasma` int DEFAULT 0,
	`observacoes` text,
	`conciliadoPorId` int,
	`conciliadoPorNome` varchar(255),
	`conciliadoEm` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fechamentos_diarios_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transacoes_rede` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fechamentoDiarioId` int NOT NULL,
	`dataVenda` datetime NOT NULL,
	`horaVenda` varchar(10),
	`statusVenda` varchar(50),
	`valorOriginal` int NOT NULL,
	`valorAtualizado` int,
	`valorLiquido` int,
	`modalidade` varchar(20),
	`tipo` varchar(100),
	`numeroParcelas` int DEFAULT 1,
	`bandeira` varchar(50),
	`nsuCv` varchar(50) NOT NULL,
	`taxaMdr` varchar(20),
	`valorMdr` int,
	`numeroAutorizacao` varchar(50),
	`numeroEstabelecimento` varchar(50),
	`numeroCartao` varchar(50),
	`tid` varchar(50),
	`vendaId` int,
	`pagamentoId` int,
	`statusMatching` enum('ok','divergencia_valor','nao_lancado','duplicado') DEFAULT 'nao_lancado',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `transacoes_rede_id` PRIMARY KEY(`id`)
);
